# https://taskfile.dev

version: '3'

tasks:

  install:
    sources:
      - package.json
      - yarn.lock
    cmds:
      - yarn

  dev:
    deps: [install]
    cmds:
      - npx nest start --watch

  test:
    deps: [install]
    cmds:
      - npx jest --config ./test/jest-e2e.json

  serve:
    cmds:
      - docker compose up --build -d
      - docker compose logs -f

  test:integration:
    dir: test/specs
    silent: true
    cmds:
      - hurl --test --variable API_KEY={{ .API_KEY }} *.hurl
    vars:
      API_KEY:
        sh: op read "op://Employee/OpenAI/Security/API_KEY"
